[package]
name = "collection-catalog-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
collection-catalog-core = { path = "../collection-catalog-core" }
rusqlite = { version = "0.36.0", features = ["bundled"] }
