[package]
name = "collection-catalog-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
collection-catalog-core = { path = "../collection-catalog-core" }
rusqlite = { version = "0.36.0", features = ["bundled"] }
